// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-9QwnFAhnDHfi_a3ItpOSv5yeA_CLWpo',
    appId: '1:104569501562:web:9044962da8f274fec708c3',
    messagingSenderId: '104569501562',
    projectId: 'ecolens-ad854',
    authDomain: 'ecolens-ad854.firebaseapp.com',
    storageBucket: 'ecolens-ad854.firebasestorage.app',
    measurementId: 'G-ZJ7ELLV0PJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6-R6MF1-K04dUP6VQlNGCUVa4BfkLetY',
    appId: '1:104569501562:android:6cc09cccc13f53dcc708c3',
    messagingSenderId: '104569501562',
    projectId: 'ecolens-ad854',
    storageBucket: 'ecolens-ad854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8n2OLd3s6w06SrMOqgBj34aT8jgUpMtk',
    appId: '1:104569501562:ios:8b544705133e01bcc708c3',
    messagingSenderId: '104569501562',
    projectId: 'ecolens-ad854',
    storageBucket: 'ecolens-ad854.firebasestorage.app',
    iosBundleId: 'com.example.ecolens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8n2OLd3s6w06SrMOqgBj34aT8jgUpMtk',
    appId: '1:104569501562:ios:8b544705133e01bcc708c3',
    messagingSenderId: '104569501562',
    projectId: 'ecolens-ad854',
    storageBucket: 'ecolens-ad854.firebasestorage.app',
    iosBundleId: 'com.example.ecolens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-9QwnFAhnDHfi_a3ItpOSv5yeA_CLWpo',
    appId: '1:104569501562:web:b448616bb530c0cbc708c3',
    messagingSenderId: '104569501562',
    projectId: 'ecolens-ad854',
    authDomain: 'ecolens-ad854.firebaseapp.com',
    storageBucket: 'ecolens-ad854.firebasestorage.app',
    measurementId: 'G-FJ304K1272',
  );
}
